version: '2'
services:
  mysqlDev-container:
    container_name: mysqlDev-container
    image: mysql:latest
    restart: unless-stopped
    environment:
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - sqldata:/var/lib/mysql

  devops-project:
    container_name: devops-project
    depends_on:
      - mysqlDev-container
    build: ./
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  sqldata:
