version: '3.8'

services:
  mysqlDev-container:
    image: mysql
    container_name: mysqlDev-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: devops
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  conteneur_devops_project:
    image: asmaattia/devops_project_image:latest
    container_name: conteneur_devops_project
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlDev-container:3306/devops
    depends_on:
      - mysqlDev-container
    networks:
      - app-network

volumes:
  mysql_data:
  mysql_config:

networks:
  app-network:
    driver: bridge
